---
title: Workshop de Web scraping
---

# Sobre o curso

Neste workshop, você aprenderá a extrair e estruturar dados diretamente da internet. Passaremos pelos princípios básicos de requisições web, como controlá-las por intermédio do R e como utilizá-las para baixar dados de meneira consistente e automatizada.

Os slides do curso estão disponíveis [neste link](/slides).

## Público Alvo

Estudantes, pesquisadores e profissionais que trabalham com análise de dados e precisam recorrentemente extrair dados da internet.

## Pré-requisitos

-  Conhecimento introdutório de programação em R: lógica de programação e R base.

- Laptop com R e RStudio® instalados (quanto mais atualizados, melhor).

## Datas e Horários

Sábado, dia 23 de junho, das 9h às 18h.

## Local

Espaço Maestro
R. Maestro Cardim, 1170 Paraíso, São Paulo–SP

## Programa

-  Noções de protocolo HTTP e acesso a páginas web.

-  Pacotes httr e curl para fazer requisições HTTP e baixar arquivos com o R.

-  Pacotes xml2, rvest e jsonlite para obter informações estruturadas de arquivos .xml, .html e .json. 

-  Pacote pdftools para extrair informações de PDFs. 
